# The file is generated automatically
# Do not remove this file and change it
version: '3.1'

services:
  main_app:
    container_name: {{ value.id }}
    image: totalplatform/run:npm
    restart: always
    volumes:
      - {{ value.www }}:/www
      - {{ value.npm }}:/node_modules
    environment:
      - VIRTUAL_MAX_UPLOAD={{ value.maxupload }}
      - VIRTUAL_HOST={{ value.host }}
      - VIRTUAL_PORT=8000
      - DISABLE_ACCESS_LOGS=1

networks:
  default:
    name: proxy
    external: true